#!/usr/bin/env python3
"""Streamlit presentation layer for transient Phase 7 dashboard snapshots."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATA_DIR = REPOSITORY_ROOT / ".runtime/dashboard"
DATA_DIR = Path(
    os.environ.get("DASHBOARD_DATA_DIR", str(DEFAULT_DATA_DIR))
).expanduser()
REFRESH_INTERVAL = "2s"


def read_snapshot(name: str) -> list[dict[str, Any]]:
    """Read one atomically replaced JSON list without breaking a dashboard refresh."""
    try:
        with (DATA_DIR / name).open("r", encoding="utf-8") as handle:
            content = json.load(handle)
    except (FileNotFoundError, json.JSONDecodeError, OSError, UnicodeError):
        return []
    if not isinstance(content, list):
        return []
    return [item for item in content if isinstance(item, dict)]


def valid_metrics(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    required = {
        "window_end",
        "event_count",
        "event_rate",
        "attack_count",
        "attack_rate",
        "status",
    }
    return sorted(
        (row for row in rows if required.issubset(row)),
        key=lambda row: str(row["window_end"]),
    )


def render_status(status: str) -> None:
    message = f"Current status: {status}"
    if status == "Normal":
        st.success(message)
    elif status == "Warning":
        st.warning(message)
    elif status == "Critical":
        st.error(message)
    else:
        st.info(f"Current status unavailable: {status}")


def render_alerts(alerts: list[dict[str, Any]]) -> None:
    st.subheader("Recent predicted-Attack alerts")
    st.caption(
        "Scenario and source label are simulation/evaluation metadata. "
        "They are not multiclass model predictions."
    )
    if not alerts:
        st.info("No predicted Attack alerts in the current runtime.")
        return

    newest_first = sorted(
        alerts,
        key=lambda row: (
            str(row.get("event_timestamp", "")),
            str(row.get("topic", "")),
            int(row.get("partition", -1)),
            int(row.get("offset", -1)),
        ),
        reverse=True,
    )
    display_rows = [
        {
            "Time": row.get("event_timestamp", ""),
            "Prediction": row.get("prediction_label", ""),
            "Scenario (simulation)": row.get("scenario", ""),
            "Source label (ground truth metadata)": row.get("source_label", ""),
        }
        for row in newest_first
    ]
    st.dataframe(display_rows, hide_index=True, width="stretch")


@st.fragment(run_every=REFRESH_INTERVAL)
def render_realtime_content() -> None:
    metrics = valid_metrics(read_snapshot("metrics.json"))
    alerts = read_snapshot("alerts.json")

    if not metrics:
        st.info("Waiting for realtime analytics data...")
        render_alerts(alerts)
        return

    latest = metrics[-1]
    render_status(str(latest["status"]))
    st.caption(f"Latest analytics window ended at {latest['window_end']}")

    event_rate = float(latest["event_rate"])
    attack_rate = float(latest["attack_rate"])
    kpi_columns = st.columns(4)
    kpi_columns[0].metric("Event Rate", f"{event_rate:.1f} events/s")
    kpi_columns[1].metric("Predicted Attack Rate", f"{attack_rate:.1%}")
    kpi_columns[2].metric("Events in Current Window", int(latest["event_count"]))
    kpi_columns[3].metric(
        "Predicted Attacks in Current Window", int(latest["attack_count"])
    )

    trend_data = pd.DataFrame(metrics)
    trend_data["window_end"] = pd.to_datetime(
        trend_data["window_end"], utc=True, errors="coerce"
    )
    trend_data = trend_data.dropna(subset=["window_end"]).sort_values("window_end")

    st.subheader("Event-rate trend")
    st.line_chart(trend_data, x="window_end", y="event_rate")

    st.subheader("Predicted attack-rate trend")
    attack_trend = trend_data[["window_end", "attack_rate"]].copy()
    attack_trend["Predicted Attack Rate (%)"] = attack_trend["attack_rate"] * 100.0
    st.line_chart(
        attack_trend,
        x="window_end",
        y="Predicted Attack Rate (%)",
    )

    render_alerts(alerts)


def main() -> None:
    st.set_page_config(
        page_title="IoT Realtime Monitor",
        page_icon="🛡️",
        layout="wide",
    )
    st.title("IoT Network Intrusion Detection — Realtime Monitor")
    st.caption("Predictions are generated by the frozen binary Random Forest model.")
    render_realtime_content()


main()
